# Implementing Model

In [6]:
import pickle
import numpy as np

In [7]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

### Assume Data as
- Pcalss
- Gender
- Age
- SibSp
- ParCh
- Fare
- Embarked

In [9]:
test_input = np.array(['2','male','31.0','0','0','10.5','S'],dtype='object').reshape(1,7)

In [12]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))`

C:\Users\Nitesh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [13]:
test_input_sex

array([[0., 1.]])

In [11]:
test_input_embarked = ohe_embarked.transform(test_input[:,1].reshape(1,1))

In [14]:
test_input_embarked

array([[0., 0., 0.]])

In [18]:
test_input_age = test_input[:,2].reshape(1,1)

In [19]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

### Predicting Survival

In [22]:
clf.predict(test_input_transformed)
# The Passenger would Survived

array([1], dtype=int64)

# Made by Nitesh Addagatla
- LinkidIn: https://www.linkedin.com/in/nitesh-addagatla
- GitHub: https://github.com/niteshA04
- Kaggle: https://www.kaggle.com/niteshaddagatla